#!/bin/bash

echo "🎯 Foundry Fork 项目演示 - 无需外部 RPC"
echo "================================"

echo ""
echo "📋 项目概述:"
echo "这是一个完整的 Foundry Fork 项目，演示如何:"
echo "  ✅ Fork 主网到指定区块高度"
echo "  ✅ 与真实DeFi协议交互"  
echo "  ✅ 进行时间旅行测试"
echo "  ✅ 模拟复杂交易场景"

echo ""
echo "📁 项目结构:"
find . -name "*.sol" -o -name "*.sh" -o -name "*.toml" | head -10 | while read file; do
    echo "  📄 $file"
done

echo ""
echo "🛠️ 核心功能:"
echo "  🔧 ForkTester.sol - 主要合约，包含所有Fork测试功能"
echo "  🧪 ForkTest.t.sol - 完整的测试套件"
echo "  🚀 start_fork.sh - 一键启动Fork网络"
echo "  📦 deploy_fork.sh - 自动部署脚本"
echo "  🧪 run_tests.sh - 测试运行脚本"

echo ""
echo "🔍 合约功能预览:"
echo "contract ForkTester {"
echo "  // 检查代币余额"
echo "  function checkTokenBalance(address token, address user) external"
echo "  "
echo "  // 模拟代币转账"
echo "  function simulateTransfer(address token, address from, address to, uint256 amount) external"
echo "  "
echo "  // 获取区块信息"
echo "  function getBlockInfo() external view returns (uint256, uint256, bytes32)"
echo "  "
echo "  // 检查是否在Fork环境"
echo "  function isForkedNetwork() external view returns (bool)"
echo "}"

echo ""
echo "🚀 使用方法:"
echo "1. 配置 RPC URL:"
echo "   cp .env.example .env"
echo "   # 编辑 .env 文件，填入你的 Alchemy/Infura API Key"
echo ""
echo "2. 启动 Fork 网络:"
echo "   ./start_fork.sh mainnet 18500000"
echo ""
echo "3. 运行测试:"
echo "   ./run_tests.sh all"
echo ""
echo "4. 部署合约:"
echo "   ./deploy_fork.sh"

echo ""
echo "💡 高级用法示例:"
echo "# Fork 特定区块进行历史分析"
echo "anvil --fork-url \$RPC_URL --fork-block-number 18000000"
echo ""
echo "# 在测试中进行时间旅行"
echo "vm.roll(block.number + 100);  // 前进100个区块"
echo "vm.warp(block.timestamp + 3600);  // 前进1小时"
echo ""
echo "# 给任意地址分配资产进行测试" 
echo "vm.deal(testAccount, 100 ether);  // 分配ETH"
echo "deal(USDC, testAccount, 10000 * 1e6);  // 分配USDC"

echo ""
echo "🎯 实际应用场景:"
echo "  📊 DeFi协议测试和集成"
echo "  🔄 MEV策略回测和验证"  
echo "  🛡️ 智能合约安全审计"
echo "  📈 历史数据分析和重现"
echo "  🧪 复杂交易逻辑测试"

echo ""
echo "⚠️  注意事项:"
echo "  • 需要有效的以太坊 RPC URL (Alchemy/Infura/QuickNode等)"
echo "  • Fork 会消耗一定内存和带宽"
echo "  • 免费 RPC 服务通常有请求速率限制"
echo "  • 太老的区块可能无法访问"

echo ""
echo "✅ 项目搭建完成!"
echo "📖 查看 readme.txt 获取详细文档"
echo "🔧 配置 .env 文件后即可开始使用"

echo ""
echo "🌟 这个项目演示了完整的 Foundry Fork 工作流，是学习 Web3 开发的绝佳实践！"